# Generated by Django 5.0 on 2024-01-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_orderitem_transaction_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='ShippingAddres',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='transaction_id',
        ),
    ]
