# Generated by Django 5.1.2 on 2024-10-18 11:09

from django.db import migrations


class Migration(migrations.Migration):
    
    def custom_task(self, scheme_editor):
        Student = self.get_model("student", "Student")
        for student in Student.objects.all():
            student.firstname = student.firstname.capitalize()
            student.save()

    dependencies = [
        ('student', '0004_alter_student_teacher'),
    ]

    operations = [
        migrations.RunPython(custom_task, migrations.RunPython.noop)
    ]
